- main.c
loop=0
This should fix the logic when loop=0. It will then both execute the sending of bootcode.bin and the second stage boot server (sending start.elf).
Tested on PiZero and Slice1. Slice1 is put in MSD mode with access to eMMC.
Here the dmesg output from Slice1:
```
[ 8318.498490] usb 1-1.4: USB disconnect, device number 65
[ 8324.113440] usb 1-1.4: new full-speed USB device number 66 using dwc_otg
[ 8324.223731] usb 1-1.4: New USB device found, idVendor=0a5c, idProduct=2763
[ 8324.223747] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 8324.223755] usb 1-1.4: Product: BCM2708 Boot
[ 8324.223763] usb 1-1.4: Manufacturer: Broadcom
[ 8325.667562] usb 1-1.4: USB disconnect, device number 66
[ 8326.923469] usb 1-1.4: new high-speed USB device number 67 using dwc_otg
[ …
```
> Execute both sending bootcode.bin and second stage boot server when

- main.c
Enable immediately stdout flushing for better integration with automated sdout parsing from external application.
> Flush stdout buffer immediately

- main.c
The BCM2711 can also boot in USB device mode. Note that the boot ROM
code now sets the iSerialNumber to 3, but it does not expect the
second stage boot server, instead it downloads a single image over
USB.
Signed-off-by: Petr Tesarik <petr@tesarici.cz>
> Add support for Pi4

- main.c
The second stage can/will support file-server so don't force
bootcode.bin for 2711. The second stage will (probably) reply
with SerialNumber==1 when it wants the file-server as on Pi3.
> Fix serial check for BCM2838 / BCM2711

- main.c
With recent kernels I get timeouts booting Linux with rpiboot, after increasing the timeout to 3000 I have no issues.
Debugging I see the ep_read call after ReadFile: cmdline.txt (before it tries to retrieve recovery.img/kernel.img) takes around 2.1-2.2 seconds which looks to be related to the size of the iniramfs I'm using.
> Change timeout in ep_read to 3 seconds

- main.c
> Avoid warning 'libusb_set_debug deprecated'

- main.c
It's possible that SerialNumber=3 might be received twice due to
differences in timing causing rpiboot to exit too early i.e. before
the second stage has started.
Tweak the loop condition to handle this.
> 2711: Fix handling of serial numbers in single shot mode

- main.c
Also add extra logging to indicate where the file was loaded
from to make it more obvious where a file is loaded from.
Update Windows installer
This was a added as a separate commit and inadvertenly dropped for the larger CM4 update.
> Don't load bootcode from the overlay directory

- Readme.md
Adds instructions for macOS users.
It will mainly help with the perception that this only works on ubuntu.
You can also use this on macOS without a problem.
> readme: add macOS build step

- Makefile
Add `install` target for  executable and default
`bootcode.bin`/`bootcode4.bin` and
`start.elf`/`start4.elf` files.
Update `uninstall` target.
> Fix `install` and `uninstall` targets in Makefile.

- Makefile
- Readme.md
- main.c
This PR resolves https://github.com/raspberrypi/usbboot/issues/81, and closes https://github.com/raspberrypi/usbboot/pull/25.
This is a very simple change that uses `pkg-config` to locate `libusb-1.0` rather than assuming its path, allowing users who have installed `libusb-1.0` with homebrew to successfully build with `make`.
---
Thanks to @khorben (PR: #25) and @Parnoud (Issue: https://github.com/raspberrypi/usbboot/issues/81#issuecomment-851637615) for laying out the solution.
> Use pkg-config to locate libusb-1.0

- Makefile
- main.c
Update rpiboot to emit the build-date and version in order so that this visible in bug reports.
> rpiboot: Add build date and version

- tools/update-pieeprom.sh
Previously, relative paths would confuse the file name generation regex.
With this change, only the final '.' character is matched as the
beginning of the file extension.
> Fixed regex for sig file to replace only extension

- tools/update-pieeprom.sh
When not signing the configuration (no -k option), there's no
$TMP_CONFIG file and `test -f "$TMP_CONFIG"` is false. The whole line
becomes false and the script exists 1 for `set -e`.
This commit fixes that by moving the test to `if` condition.
> tools/update-pieeprom.sh: Fix cleanup exiting 1

- Readme.md
Follow up to https://github.com/raspberrypi/usbboot/pull/27,  you probably shouldn't be encouraging sudo - anyway, this should help inform others that it isn't actually necessary.
> Add no sudo hint

- main.c
Previously two commits added a fallback fmemopen for OS X/BSD that
didn't support fmemopen, then fixed some of the ifdef logic around it.
Unforunately the logic was backwards, as libc implementations do not
define _POSIX_C_SOURCE in order to advertise features.  Instead the
user defines _POSIX_C_SOURCE to control which definitions are
available.
Check _POSIX_VERSION to see if the libc is new enough to implement
fmemopen.  If it is too old, assume that we're on a BSD compatible
system and use the fallback fmemopen that depends on funopen.
This solves the problem for some environments, but is still incorrect
as it will try to use the fallback even on a system that does not
include funopen.
Fixes: 45c7237 (Fixup for recent firmware inclusion changes (#34))
Fixes: 17f6b01 (Fix cross-platform …
> main: check _POSIX_VERSION for fmemopen

- tools/rpi-eeprom-digest
Wrap the OpenSSL commands to verify the RSA signature in a .sig file for a given image. This could be used to verify a signed boot image or EEPROM image before attempting to install it.
> rpi-eeprom-digest: Add an option to verify RSA signed files.

- tools/rpi-otp-private-key
This script requires a newer firmware release should should be available soon via rpi-update.
> tools: vcmailbox wrappers for managing 256 bit OTP private key

- main.c
Move the port and path filter match logic up to prevent rpiboot from loading any files if the device does not meet the given criteria. For devices that should be ignored, the current implementation generates numerous messages such as "Loading embedded: bootcode.bin." Because the check occurs AFTER the filters have been evaluated, file handling takes place even for ignored devices.
The reported behavior can be tested by calling rpiboot with port number (eg. `-1`) or path (eg. `-p 1-1.3.4.4.1`)
> Skip devices which don't match filter criteria

- tools/rpi-otp-private-key
Also add full stop, and remove hyphen which shouldn't be there.
> rpi-otp-private-key: fix typo

- Readme.md
When building on MacOS 12.6 with Homebrew 3.6.13 I was unable to build without first exporting the `PKG_CONFIG_PATH`. Although the build does explicitly say to set this I added it to the MacOS instructions.
> Updated README for PKG_CONFIG_PATH env variable

- secure-boot-recovery/README.md
The old sentence didn't really make sense. Also a bit further down it says "prevents downgrades to bootloader versions that don't support secure boot." which is what the changed sentence was meant to mean. I fixed that and also changed to wording to make it more clear.
> Fix typo that resulted in opposite meaning (does -> doesn't)

- tools/rpi-otp-private-key
-o <offset> -l <length>
Offset and length are specified in words (4 bytes) Default is offset=0 length=8
2711 supports 8 words. 2712 supports 16 words.
> Add options to set the key offset and length

- secure-boot-recovery/README.md
change `revoke_revkey=1` to `revoke_devkey=1` as (if i've understood things correctly) it should be.
> Fix typo in secure-boot-recovery docs

- main.c
Add a new command line flag to select the compute module by serial number. This requires walking the USB device list, finding the serial of each and comparing it against the supplied string.
This mechanism does not bypass the VID/PID checks.
Untested at time of PR. Review with extreme caution.
> rpiboot: Allow selecting by serial number

- main.c
> rpiboot: Fixup USB VID typo

- debian/changelog
- debian/control
- debian/rpiboot.install
- debian/rules
- firmware/2712/pieeprom-2024-04-17.bin
- firmware/2712/pieeprom.bin
Also, slightly simplify the packaging of the firmare to avoid specifying the version number in both the APT meta data and via the symlink.
> firmware: Update 2712 to 2024-04-20 release

- firmware/2711/pieeprom.bin
- firmware/2711/recovery.bin
Update to the latest Pi4 firmware/recovery.bin for Pi4B specific OTP provisioning fixes plus improved logging during secure-boot provisioning.
> firmware: 2711: Update to latest Pi4 firmware pieeprom-2024-05-17.bin

- firmware/2711/pieeprom.bin
Move to this release because it resolves some issues booting from the BCM XHCI USB port on CM4 / CM4S.
> firmware: 2711: Move to the 2024-07-30 release

- Readme.md
- secure-boot-recovery5/README.md
Secure-boot on 2712 is a port of the 2711 functionality. It's in BETA pending security testing and feedback on tooling/provisioning.
> secure-boot: 2712: Update to docs to indicate BETA status

- mass-storage-gadget64/README.md
- secure-boot-recovery5/README.md
Fix typo in mass-storage-gadget64 and fix formatting in secure-boot-recovery5 README.md
> typo fixes

- tools/make-boot-image
Insisting on mkfs.fat being found in /sbin is wrong. Some distros might have it somewhere else, e.g. /bin or, if usrmerge is not done, in /usr/sbin.
Also, when using a meta-buildsystem like Yocto or buildroot, the build dependencies will have made sure to make mkfs.fat available somewhere in $PATH, but without the build host necessarily having mkfs.fat at all.
> make-boot-image: remove hard-coded path to mkfs.fat utility

- tools/make-boot-image
Currently, the script must be run as the root user due to the use of losetup/mount. That is unnecessary, and sometimes impossible (e.g. in the context of an automated meta-build system like Yocto).
The mcopy command, typically provided by an "mtools" package, allows one to write files to and from a FAT filesystem image. Use that if available, and add a little hint that one could install mtools if the script is invoked as non-root.
> make-boot-image: use mcopy if available

- Makefile
Originally part of #2, this patch has been carried in Buildroot since almost 8 years now.
@tpetazzoni, thanks for the original patch!
> Makefile: allow passing CFLAGS/LDFLAGS

- debian/control
These boards require firmware 2024-09-23 or newer.
> debian: Require rpi-eeprom 26.3 or newer for CM5 / Pi500 support

- mass-storage-gadget64/sign.sh
`./sign.sh <key>`
produces error:
> Signing OS image /home/kusov/development/usbboot/mass-storage-gadget64/bootfiles.original.bin
> Signing 2712/bootcode5.bin
> Signing firmware in 2712/bootcode5.bin
> ./sign.sh: 20: rpi-sign-bootcode: not found
> Failed to sign bootcode5.bin
> mass-storage-gadget64: fix invokes of extra tools in sign.sh

- Makefile
Long ago, the makefile logic made use of the xxd tool to generate a C array from a binary file. That was removed in commit 768c0563d110 ("Add cross platform method of building in a binary!"), in favor of the little bin2c helper, presumably because the xxd tool is not necessarily available everywhere.
However, that then introduced the implicit assumption that ${CC} is a compiler meant for producing binaries for the current build host, and thus breaks down in a cross-build setup, such as when trying to integrate this in a Yocto recipe.
Adapt the logic so that when xxd is available, use that, and if not, honour a CC_FOR_BUILD environment variable if set, letting that default to $(CC). This way, a cross-build environment can either make sure to add build-time dependency on xxd-native, or …
> Makefile: make it work better in a cross-build scenario

- win32/install_script.nsi
- win32/rpi-mass-storage-gadget.bat
- win32/rpi-mass-storage-gadget64.bat
Change the shortcut links to indicate that rpiboot.exe should be used for cm-cm2-cm3 and that the mass-storage-gadget should be used for cm4-cm5
Also, update the mass-storage-gadget to provide an information message / prompt after starting the gadget service.
> win32 - Installer - Update shortcut names to reflected supported HW version

- recovery5/boot.conf
- secure-boot-recovery5/boot.conf
* Enable network boot
* Fix USB/NVMe order (NVMe should be first)
* Remove redundant SIGNED_BOOT=1 from secure-boot-recovery5
* Set POWER_OFF_ON_HALT=1 - recommended for CM5 which is the primary platform for rpiboot.
> 2712: Update recommended boot.conf for default provisioning setup

- main.c
Extend the directory search to try ./mass-storage-gadget64 if the -d argument is not specified and the directory is not specified in the install directory.
Improve the error message to suggest passing the -d argument.
> pi5: Improve path handling if bootfiles.bin is not found

- mass-storage-gadget64/bootfiles.bin
Fixes: https://github.com/raspberrypi/usbboot/issues/275
> mass-storage-64: Restore symlink to bootfiles.bin

- mass-storage-gadget64/README.md
Fixes: #278
Also fixes the path to the expected output image.
Given that I attempted the documented build on my host Ubuntu 22.04.5 LTS system, and the maintainer reported building under the same, it seems reasonable to suggest the built-in upstream docker image as a more host-independent build environment that is known to work.
> mass-storage-64: Suggest docker build environment

- main.c
Change the 2711 default behaviour to use mass-storage-gadget64 if the directory argument is not specified.
The old msd.elf can still be run by executing -d msd but this is not recommended because it is much slower than the Linux mass-storage-gadget. 
N.B The msd.elf does not and will not support NVMe / USB block devices.
> rpiboot: Use mass-storage-gadget-64 by default on BCM2711

- main.c
If the -d DIR directory argument is specified and bootfiles.bin is in use then give the local file DIR/CHIP/filename a higher priority than the file within the bootfiles.bin.
This makes it easier to override files within bootfiles.bin.
> Add support for overriding files in bootfiles.bin

- secure-boot-example/README.md
Fix minor typo in secure-boot-example/README.md.
> secure-boot-example/README.md: Fix typo

- debian/70-rpiboot.rules
- debian/rpiboot.install
Ensure that bootrom mass storage device is not marked as authorized.
Package mass-storage-gadget64-cm3
> Pi Zero 2 W Debian Packaging Changes

- Makefile
Modified the BUILD_DATE variable in the Makefile to use the appropriate date command for macOS, ensuring build runs on OSx.
Was otherwise failing with:
```sh
xxd -i msd/bootcode.bin > msd/bootcode.h
xxd -i msd/start.elf > msd/start.h
xxd -i msd/bootcode4.bin > msd/bootcode4.h
date: illegal time format
usage: date [-jnRu] [-I[date|hours|minutes|seconds]] [-f input_fmt]
[-r filename|seconds] [-v[+|-]val[y|m|w|d|H|M|S]]
[[[[mm]dd]HH]MM[[cc]yy][.SS] | new_date] [+output_fmt]
cc -Wall -Wextra -g   -o rpiboot main.c bootfiles.c decode_duid.c `pkg-config --cflags --libs libusb-1.0` -DGIT_VER="\"5a62a2cc\"" -DPKG_VER="\"local\"" -DBUILD_DATE="\"\"" -DINSTALL_PREFIX=\"/usr/local\" 
```
> Update Makefile to handle `date` for macOS compatibility

- mass-storage-gadget64/README.md
- mass-storage-gadget64/sign.sh
- secure-boot-example/example-hsm-wrapper
- secure-boot-recovery5/README.md
- test/validate-hsm-wrapper.sh
- tools/update-pieeprom.sh
Add support for HSMs by extracting by adding an interface where the PKCS#1 v1.5 signature (RSA2048 SHA256) generation can be implemented by a dedicated helper script.
This approach makes it easier to support multiple HSM APIs without adding specific knowledge of HSMs to this code.
The algorithm choice is provided by the API but is very unlikely to change because that would require updating the BCM2711 / BCM2712 bootroms.
A software implemenation (secure-boot-example/example-hsm-wrapper) is provided to define the interface and act as reference for unit tests.
> Add a Hardware Security Module wrapper script interface

- secure-boot-recovery/.gitignore
- secure-boot-recovery/README.md
- secure-boot-recovery/boot.conf
- secure-boot-recovery/config.txt
- secure-boot-recovery5/.gitignore
- secure-boot-recovery5/README.md
- secure-boot-recovery5/config.txt
Automatically set revoke_devkey if program_pubkey=1 because revoke_devkey=1 should always be set if secure-boot is used in production.
Tidyup the documentation for SIGNED_BOOT.
> secure-boot-recovery: program_pubkey now automatically sets revoke_devkey=1

- bootfiles.c
Move "not found" and "found" messages to -vv
> bootfiles: Reduce the verbosity of bootfiles message

- main.c
Displays the version string. For local builds the git hash is specified. Otherwise, for APT releases the pkg-version is specified.
There is no semantic verison number.
See: #308
> rpiboot: Add -V/--version to display the version string.

- tools/rpi-make-boot-image
```
rpi-make-boot-image: Fix FAT12 image generation
mkfs.vfat -F option was not specified which caused mkfs to deduce the FAT type
on it's own. For a small enough image FAT12 would be selected.
805a4fda37cf580d4d9734a9ab6ddbf1d1b18ea9 introduced cluster calculation
function that ends up only using FAT32 or FAT16. Creating a small image
would fail with message : mkfs.fat: Not enough or too many clusters
for filesystem - try less or more sectors per cluster
```
> rpi-make-boot-image: Fix FAT12 image generation

- tools/update-pieeprom.sh
If using an HSM, the public key is not derived, rather taken as an input parameter. In that case, however, it can happen that the user specifies a mismatching pubkey. This PR adds a check to make sure the pubkey belongs to the signature before embedding it further.
Fixes https://github.com/raspberrypi/usbboot/issues/319.
> tools: verify HSM signature based on provided public key

- Readme.md
Looked up the required packages from dnf to build rpiboot.
Restructured the section of the readme file accordingly.
> Restructured readme to add Fedora/RHEL dnf dependencies

- eeprom-erase/bootcode5.bin
Rpiboot on Pi 5(00) / CM5 looks for bootcode5.bin. Add a symlink from 2712/recovery.bin to bootcode5.bin so the erase procedure also works for these boards. This mirrors the existing setup in recovery5/.
> eeprom-erase: Add symlink for bootcode5.bin

- main.c
This series implements / re-uses device specific file lookup for rpiboot. With this existing targets like `recovery5` and `recovery` can be merged and thus simplify the user experience. Also during automated setups it helps as the abstraction is handled by `rpiboot` (we currently use this kind of automatism for having a unified recovery  / firmware update procedure in production).
As example the recovery target is merged. mass-storage-gadget64 and secure-boot-recovery and be probably also merged. 
Looking forward for thoughts about this approach
> RFC: Add lookup for device specific files

- mass-storage-gadget64-cm3
The updated version of bootcode.bin supports boot.img ramdisks PiZero2W, CM3, CM0. Drop the redundant 64-bit mass-storage implemenation where files are loaded from the bootfiles.bin tar file instead of boot.img.
> mass-storage-gadget: Remove mass-storage-gadget64-cm3
